version: 0.2

env:
  variables:
    BRANCH_NAME: “master”
    MAJOR_VERSION: “1”
    MINOR_VERSION: “0”
    GIT_REPO: “https://github.com/shubhamsharma1993/sample-node.git"
  git-credential-helper: yes

phases:
  build:
   commands:
     - cd sample-node
     - git config --global user.email "shubham.sharma2@sourcefuse.com"
     - bash git_taging.sh
