version: 0.2

env:
 git-credential-helper: yes

phases:
  install:
    commands:
      - apt-get update -y && apt-get install -y git
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
     - echo "branch name is:" $BRANCH_NAME
     - echo "tag name:" $TAG_NAME 
     - echo “machine git-codecommit.us-east-1.amazonaws.com” >> ~/.netrc
     - echo “login $GIT_USER” >> ~/.netrc
     - echo “password $GIT_PASS” >> ~/.netrc
     - echo $BRANCE_NAME
     - echo $GIT_REPO
     - git clone -b $BRANCH_NAME https://github.com/shubhamsharma1993/sample-node.git --branch $TAG_NAME --single-branch
  build:
   commands:
     - cd sample-node
     - git config --global user.email "shubham.sharma2@sourcefuse.com"
     - npm build

artifacts :
   files :
    - output.zip
