version: 0.2

env:
 parameter-store:
    build_ssh_key: "build_ssh_key"
 git-credential-helper: yes
 
phases:
  install:
    commands:
      - apt-get update -y && apt-get install -y git
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
     - mkdir -p ~/.ssh
     - echo "$build_ssh_key" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - echo “login $GIT_USER” >> ~/.netrc
     - echo "branch name is:" $BRANCH_NAME
     - echo "tag name:" $TAG_NAME 
     - echo “machine git-codecommit.us-east-1.amazonaws.com” >> ~/.netrc
     - echo $BRANCE_NAME
     - echo $GIT_REPO
     - git clone https://github.com/shubhamsharma1993/sample-node.git 
  build:
   commands:
     - cd sample-node
     - git config --global user.email "shubham.sharma2@sourcefuse.com"
     - npm build
artifacts:
   files:
     - '**/*'

